window.AssistantDemoData = {
  generated_at: new Date().toISOString(),
  is_admin: false,
  current_user: {},
  admin: { users: [], audit_logs: [], allowed_count: 0, blocked_count: 0 },
  balance_total_text: "0 UZS",
  balance_total: 0,
  balances: [],
  today: { expense_text: "0 UZS", income_text: "0 UZS", net_text: "0 UZS", expense: 0, income: 0, net: 0 },
  week: { expense_text: "0 UZS", income_text: "0 UZS", net_text: "0 UZS", expense: 0, income: 0 },
  month: { expense_text: "0 UZS", income_text: "0 UZS", net_text: "0 UZS", expense: 0, income: 0 },
  categories: [],
  category_limits: [],
  finance_warnings: [],
  recent_transactions: [],
  transactions: [],
  reminders: [],
  active_reminders: [],
  completed_reminders: [],
  prayer: {
    city: "Toshkent",
    enabled: false,
    enabled_keys: [],
    minutes_before: 0,
    source: "Hozircha offline hisoblash",
    next: { name: "Asr", time: "17:17" },
    times: [
      { key: "fajr", name: "Bomdod", time: "03:33", enabled: false, can_notify: true },
      { key: "sunrise", name: "Quyosh", time: "05:20", enabled: false, can_notify: false },
      { key: "dhuhr", name: "Peshin", time: "12:20", enabled: false, can_notify: true },
      { key: "asr", name: "Asr", time: "17:17", enabled: false, can_notify: true },
      { key: "maghrib", name: "Shom", time: "19:22", enabled: false, can_notify: true },
      { key: "isha", name: "Xufton", time: "21:01", enabled: false, can_notify: true },
    ],
  },
  settings: {
    daily_expense_limit: 0,
    daily_expense_limit_text: "Belgilanmagan",
    daily_report_enabled: true,
  },
  cities: ["Toshkent", "Samarqand", "Buxoro", "Andijon", "Farg'ona", "Namangan"],
};
